#!/usr/bin/env bash

if ! command -v foreman &> /dev/null
then
  echo "Installing foreman..."
  gem install foreman
fi

while getopts "p" option
do 
  case "${option}"
    in
    p)polling=1;;
    *);;
  esac
done

if [ $polling -eq 1 ]
then
  echo "[INFO] Enabled polling for css processing!"
  foreman start -f Procfile.dev -m all=1,css=0
else 
  foreman start -f Procfile.dev -m all=1,css_polling=0
fi
