name: Native Gems
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ruby", "x64-mingw32", "x64-mingw-ucrt", "x86_64-darwin", "arm64-darwin", "x86_64-linux", "arm-linux"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler: latest
          bundler-cache: true
      - run: "bundle exec rake gem:${{matrix.platform}}"
      - uses: actions/upload-artifact@v4
        with:
          name: gem-${{matrix.platform}}
          path: pkg
          retention-days: 1

  vanilla-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-ruby
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss 2>&1 | fgrep 'ERROR: Cannot find the tailwindcss executable'"

  linux-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  linux-musl-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2-alpine
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "apk add build-base" # to compile racc, etc.
      - run: "gem update --system" # let's make sure the latest is working for us (upstream test, see #200)
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  linux-arm-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gem-arm-linux
          path: pkg
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v "$(pwd):/test" -w /test --platform=linux/arm/v7 ruby:3.2 \
            /bin/bash -c "
              set -ex
              gem install pkg/tailwindcss-rails-*.gem
              tailwindcss --help
            "

  darwin-x86_64-install:
    needs: ["package"]
    runs-on: macos-13
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-x86_64-darwin
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  darwin-arm64-install:
    needs: ["package"]
    runs-on: macos-14
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-arm64-darwin
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  windows-install:
    needs: ["package"]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v3
        with:
          name: gem-x64-mingw32
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  windows-ucrt-install:
    needs: ["package"]
    runs-on: windows-2022
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-x64-mingw-ucrt
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"
